export const storefrontCopy = {
  es: {
    banner1: "🥖 15% Dcto en compras mayores a $100",
    banner2: "📦 Suscribete y ahorra 15%",
    navBakery: "Panaderia",
    navAbout: "Nosotros",
    navContact: "Contacto",
    btnStart: "Pedir Ahora",
    heroTitle1: "Hornea",
    heroTitle2: "El Pan",
    heroSticker1: "Sabroso",
    heroSticker2: "Crujiente",
    heroSticker3: "Fresco",
    heroSubtitle: "Pan y bolleria premium hechos desde cero",
    heroDesc: "Elaboramos productos artesanales de la mas alta calidad para elevar la oferta de tu negocio. Especialistas en pedidos al por mayor y eventos.",
    btnOrder: "Ordenar Ya",
    btnBlog: "Blog Panadero",
    featSticker: "Para toda<br/>la familia",
    featTitle: "Tu Unica",
    featTitle2: "Dosis de Deleite",
    featSubtitle: "Estandar Gourmet",
    featUnits: "/ 50 uds",
    featDesc: "Todos nuestros panes tienen una corteza espectacular y una miga tierna en su repertorio y este es uno de nuestros favoritos.",
    gridTitle: "Productos que horneamos a diario -",
    badgeSourdough: "Masa Madre",
    badgeBrioche: "Brioche",
    bentoTitle: "Por que hornear se considera un arte?",
    bentoDesc: "Su experiencia juega un papel fundamental en la forma de trabajar. Los panaderos usan sabores y atractivo visual para producir una obra de arte comestible. Cada pliegue y corte es intencional.",
    btnLearn: "Aprende Mas",
    shopTitle: "Menu Completo",
    shopSubtitle: "Venta al por mayor y Catering",
    shopSticker: "Aviso de min 48h",
    adminTitle: "Panel de Control",
    btnExitAdmin: "Salir",
    adminSubtitle: "Ordenes Recientes",
    adminStatus: { Pending: "Pendiente", Baking: "Horneando", Ready: "Listo" },
    adminNoOrders: "Sin ordenes",
    cartTitle: "Tu Bolsa",
    cartEmpty: "Tu bolsa esta vacia.",
    cartQty: "Cant",
    cartUnits: "uds",
    cartDateLabel: "Fecha de Entrega",
    cartDateSub: "Req. 48h para fermentacion.",
    cartNameLabel: "Nombre",
    cartNamePlaceholder: "Tu nombre o negocio",
    cartContactChannelLabel: "Canal",
    cartContactValueLabel: "Contacto",
    cartContactValuePlaceholder: "Email, telefono o WhatsApp",
    cartNotesLabel: "Notas",
    cartNotesPlaceholder: "Alergias, horario de entrega o detalles extra",
    cartChannelEmail: "Email",
    cartChannelPhone: "Telefono",
    cartChannelWhatsapp: "WhatsApp",
    cartTotal: "Total",
    btnCheckout: "Ir a Pagar",
    btnCheckoutLoading: "Enviando pedido...",
    cartSuccessTitle: "Pedido recibido",
    cartSuccessMessage: "Tu pedido fue creado con el numero",
    cartSuccessAction: "Seguir comprando",
    cartErrorFallback: "No pudimos crear tu pedido. Intentalo otra vez.",
    footerWholesale: "Al por mayor",
    footerContact: "Contacto",
    footerAdmin: "Panel Admin",
  },
  en: {
    banner1: "🥖 15% Off on $100+ Purchase",
    banner2: "📦 Subscribe & Save 15%",
    navBakery: "Bakery",
    navAbout: "About Us",
    navContact: "Contact",
    btnStart: "Start Baking",
    heroTitle1: "Bake",
    heroTitle2: "The Bread",
    heroSticker1: "Tasty",
    heroSticker2: "Crunchy",
    heroSticker3: "Fresh",
    heroSubtitle: "Premium bread and pastries made from scratch",
    heroDesc: "We craft the highest quality artisanal products to elevate your business offerings. Specializing in wholesale orders and events.",
    btnOrder: "Order Now",
    btnBlog: "Baking Blog",
    featSticker: "For The<br/>Whole<br/>Family",
    featTitle: "Your Only",
    featTitle2: "Dose of Delight",
    featSubtitle: "Gourmet Standard",
    featUnits: "/ 50 units",
    featDesc: "All our breads have a show-stopping crust and tender crumb in their repertoire and this is one of our favourites.",
    gridTitle: "Products We Bake Here Daily -",
    badgeSourdough: "Sourdough",
    badgeBrioche: "Brioche",
    bentoTitle: "Why is Baking Considered As Art Form?",
    bentoDesc: "Their experience plays a role in the way they work. Bakers use flavours and visual appeal to produce an edible art piece. Every fold and score is intentional.",
    btnLearn: "Learn Baking",
    shopTitle: "Full Menu",
    shopSubtitle: "Wholesale & Catering",
    shopSticker: "Min 48h Notice",
    adminTitle: "Backoffice",
    btnExitAdmin: "Exit Admin",
    adminSubtitle: "Recent Orders (Kanban)",
    adminStatus: { Pending: "Pending", Baking: "Baking", Ready: "Ready" },
    adminNoOrders: "No orders",
    cartTitle: "Your Bag",
    cartEmpty: "Your bag is empty.",
    cartQty: "Qty",
    cartUnits: "units",
    cartDateLabel: "Delivery Date",
    cartDateSub: "Req. 48h for fermentation.",
    cartNameLabel: "Name",
    cartNamePlaceholder: "Your name or business",
    cartContactChannelLabel: "Channel",
    cartContactValueLabel: "Contact",
    cartContactValuePlaceholder: "Email, phone or WhatsApp",
    cartNotesLabel: "Notes",
    cartNotesPlaceholder: "Allergies, delivery window or extra details",
    cartChannelEmail: "Email",
    cartChannelPhone: "Phone",
    cartChannelWhatsapp: "WhatsApp",
    cartTotal: "Total",
    btnCheckout: "Proceed to Checkout",
    btnCheckoutLoading: "Submitting order...",
    cartSuccessTitle: "Order received",
    cartSuccessMessage: "Your order was created with number",
    cartSuccessAction: "Keep shopping",
    cartErrorFallback: "We could not create your order. Please try again.",
    footerWholesale: "Wholesale",
    footerContact: "Contact",
    footerAdmin: "Admin Panel",
  },
} as const;

export const mockOrders = [
  { id: "ORD-001", client: "The Plaza Hotel", date: "2026-04-02", amount: 450, status: "Baking" },
  { id: "ORD-002", client: "Le Bernardin", date: "2026-04-03", amount: 210, status: "Pending" },
] as const;
