export const storefrontCopy = {
  es: {
    banner1: "🥖 15% Dcto en compras mayores a $100",
    banner2: "📦 Suscribete y ahorra 15%",
    navHome: "Inicio",
    navBakery: "Menú",
    navAbout: "Nosotros",
    navContact: "Contacto",
    btnStart: "Pedir Ahora",
    heroTitle1: "Pan",
    heroTitle2: "Con Alma",
    heroSticker1: "Sabroso",
    heroSticker2: "Crujiente",
    heroSticker3: "Fresco",
    heroSubtitle: "El arte de la panadería colombiana, ahora en Nueva York",
    heroDesc: "Cada hornada trae de vuelta los sabores de casa: queso fresco, recetas de barrio y ese aroma que sabe a recuerdo. Pedidos al por mayor y eventos.",
    btnOrder: "Ordenar Ya",
    btnBlog: "Blog Panadero",
    featSticker: "Para toda<br/>la familia",
    featTitle: "Tu Antojo",
    featTitle2: "De Siempre",
    featSubtitle: "Hecho a mano",
    featUnits: "/ 50 uds",
    featDesc: "Horneamos como en la panadería de la esquina: con tiempo, con manos y con cariño. Por eso sabe a casa, aunque estés lejos.",
    gridTitle: "Productos que horneamos a diario -",
    featuredTitle: "Recién horneados",
    featuredSeeAll: "Ver menú",
    searchPlaceholder: "Busca tu pan favorito...",
    filterAll: "Todos",
    catalogEmpty: "No encontramos panes con esa búsqueda.",
    cardUnavailable: "No disponible",
    badgeAmasijo: "Amasijos",
    badgeHojaldre: "Hojaldres",
    badgeDulce: "Dulces",
    badgeGalleteria: "Galletería",
    bentoTitle: "¿Por qué hornear es un arte?",
    bentoDesc: "Porque cada pliegue, cada corte y cada minuto de fermentación guardan una memoria. Nuestros panaderos convierten harina y paciencia en un pedacito de Colombia, una hornada a la vez.",
    btnLearn: "Aprende Mas",
    shopTitle: "Menú Completo",
    shopSubtitle: "Venta al por mayor y eventos",
    shopSticker: "Aviso de min 48h",
    shopStickerTooltip: "Cada pan se prepara con 48 horas de anticipación para respetar su fermentación.",
    adminTitle: "Panel de Control",
    btnExitAdmin: "Salir",
    adminSubtitle: "Ordenes Recientes",
    adminStatus: { Pending: "Pendiente", Baking: "Horneando", Ready: "Listo" },
    adminNoOrders: "Sin ordenes",
    cartTitle: "Tu Bolsa",
    cartEmpty: "Tu bolsa esta vacia.",
    cartQty: "Cant",
    cartUnits: "uds",
    cartDateLabel: "Fecha de Entrega",
    cartDateSub: "Req. 48h para fermentacion.",
    cartNameLabel: "Nombre",
    cartNamePlaceholder: "Tu nombre o negocio",
    cartContactChannelLabel: "Canal",
    cartContactValueLabel: "Contacto",
    cartContactValuePlaceholder: "Correo o numero de celular",
    cartAddressLabel: "Direccion",
    cartAddressPlaceholder: "Calle, numero, ciudad y codigo postal",
    cartNotesLabel: "Notas",
    cartNotesPlaceholder: "Alergias, horario de entrega o detalles extra",
    cartChannelEmail: "Correo",
    cartChannelCell: "Celular",
    cartNameRequired: "Ingresa tu nombre.",
    cartContactInvalidEmail: "Ingresa un correo valido.",
    cartContactInvalidPhone: "Ingresa un numero de celular valido.",
    cartAddressRequired: "Ingresa una direccion de entrega.",
    cartSubtotal: "Subtotal",
    cartDiscount: "Descuento",
    cartDiscountHint: "15% por compras mayores a $100",
    cartMinLabel: "Mín.",
    cartTotal: "Total",
    cartSummaryTitle: "Resumen del pedido",
    cartContinue: "Continuar al pago",
    cartKeepShopping: "Seguir comprando",
    checkoutTitle: "Finalizar pedido",
    checkoutSubtitle: "Completa tus datos para confirmar el pedido.",
    checkoutBackToCart: "Volver al carrito",
    btnCheckout: "Ir a Pagar",
    btnCheckoutLoading: "Enviando pedido...",
    cartSuccessTitle: "Pedido recibido",
    cartSuccessMessage: "Tu pedido fue creado con el numero",
    cartSuccessAction: "Seguir comprando",
    cartErrorFallback: "No pudimos crear tu pedido. Intentalo otra vez.",
    footerWholesale: "Al por mayor",
    footerContact: "Contacto",
    footerAdmin: "Panel Admin",
  },
  en: {
    banner1: "🥖 15% Off on $100+ Purchase",
    banner2: "📦 Subscribe & Save 15%",
    navHome: "Home",
    navBakery: "Menu",
    navAbout: "About Us",
    navContact: "Contact",
    btnStart: "Start Baking",
    heroTitle1: "Bread",
    heroTitle2: "With Soul",
    heroSticker1: "Tasty",
    heroSticker2: "Crunchy",
    heroSticker3: "Fresh",
    heroSubtitle: "The craft of Colombian baking, now in New York",
    heroDesc: "Every batch brings back the flavors of home: fresh cheese, neighborhood recipes and the aroma that tastes like a memory. Wholesale orders and events.",
    btnOrder: "Order Now",
    btnBlog: "Baking Blog",
    featSticker: "For The<br/>Whole<br/>Family",
    featTitle: "Your Forever",
    featTitle2: "Craving",
    featSubtitle: "Handmade",
    featUnits: "/ 50 units",
    featDesc: "We bake like the corner bakery back home: with time, with hands and with care. That's why it tastes like home, even far away.",
    gridTitle: "Products We Bake Here Daily -",
    featuredTitle: "Fresh from the oven",
    featuredSeeAll: "See menu",
    searchPlaceholder: "Search your favorite bread...",
    filterAll: "All",
    catalogEmpty: "No breads match your search.",
    cardUnavailable: "Unavailable",
    badgeAmasijo: "Cheese Doughs",
    badgeHojaldre: "Pastries",
    badgeDulce: "Sweet Breads",
    badgeGalleteria: "Cookies & Cakes",
    bentoTitle: "Why is baking an art?",
    bentoDesc: "Because every fold, every score and every minute of fermentation holds a memory. Our bakers turn flour and patience into a little piece of Colombia, one batch at a time.",
    btnLearn: "Learn Baking",
    shopTitle: "Full Menu",
    shopSubtitle: "Wholesale & events",
    shopSticker: "Min 48h Notice",
    shopStickerTooltip: "Every bread is prepared 48 hours in advance to respect its fermentation.",
    adminTitle: "Backoffice",
    btnExitAdmin: "Exit Admin",
    adminSubtitle: "Recent Orders (Kanban)",
    adminStatus: { Pending: "Pending", Baking: "Baking", Ready: "Ready" },
    adminNoOrders: "No orders",
    cartTitle: "Your Bag",
    cartEmpty: "Your bag is empty.",
    cartQty: "Qty",
    cartUnits: "units",
    cartDateLabel: "Delivery Date",
    cartDateSub: "Req. 48h for fermentation.",
    cartNameLabel: "Name",
    cartNamePlaceholder: "Your name or business",
    cartContactChannelLabel: "Channel",
    cartContactValueLabel: "Contact",
    cartContactValuePlaceholder: "Email or cell phone number",
    cartAddressLabel: "Address",
    cartAddressPlaceholder: "Street, number, city and zip code",
    cartNotesLabel: "Notes",
    cartNotesPlaceholder: "Allergies, delivery window or extra details",
    cartChannelEmail: "Email",
    cartChannelCell: "Cell",
    cartNameRequired: "Enter your name.",
    cartContactInvalidEmail: "Enter a valid email.",
    cartContactInvalidPhone: "Enter a valid cell phone number.",
    cartAddressRequired: "Enter a delivery address.",
    cartSubtotal: "Subtotal",
    cartDiscount: "Discount",
    cartDiscountHint: "15% off on orders over $100",
    cartMinLabel: "Min.",
    cartTotal: "Total",
    cartSummaryTitle: "Order summary",
    cartContinue: "Continue to checkout",
    cartKeepShopping: "Keep shopping",
    checkoutTitle: "Complete your order",
    checkoutSubtitle: "Fill in your details to confirm the order.",
    checkoutBackToCart: "Back to cart",
    btnCheckout: "Proceed to Checkout",
    btnCheckoutLoading: "Submitting order...",
    cartSuccessTitle: "Order received",
    cartSuccessMessage: "Your order was created with number",
    cartSuccessAction: "Keep shopping",
    cartErrorFallback: "We could not create your order. Please try again.",
    footerWholesale: "Wholesale",
    footerContact: "Contact",
    footerAdmin: "Admin Panel",
  },
} as const;
