import type { AdminOrder } from "@/modules/admin/domain/admin-order";

export const mockAdminOrders: AdminOrder[] = [
  {
    id: "ORD-001",
    client: "The Plaza Hotel",
    date: "2026-04-02",
    amount: 450,
    status: "baking",
    contactChannel: "email",
    contactValue: "events@plaza.test",
    address: "768 5th Ave, New York, NY 10019",
    notes: "Entrega por recepcion. Panes listos antes de las 8am.",
    items: [
      { productName: "Pandebono", quantity: 30 },
      { productName: "Croissant", quantity: 12 },
    ],
  },
  {
    id: "ORD-002",
    client: "Le Bernardin",
    date: "2026-04-03",
    amount: 210,
    status: "pending",
    contactChannel: "cell",
    contactValue: "+1 212 555 0101",
    address: "155 W 51st St, New York, NY 10019",
    notes: "Confirmar ventana de entrega durante la tarde.",
    items: [{ productName: "Pandebono", quantity: 20 }],
  },
  {
    id: "ORD-003",
    client: "Bakery Eventos",
    date: "2026-04-04",
    amount: 310,
    status: "ready",
    contactChannel: "cell",
    contactValue: "+1 917 555 0112",
    address: "43-10 Crescent St, Long Island City, NY 11101",
    notes: "Evento corporativo. Mantener empaque etiquetado.",
    items: [
      { productName: "Croissant", quantity: 20 },
      { productName: "Pandebono", quantity: 10 },
    ],
  },
  {
    id: "ORD-004",
    client: "Brooklyn Table",
    date: "2026-03-28",
    amount: 580,
    status: "delivered",
    contactChannel: "email",
    contactValue: "ops@brooklyntable.test",
    address: "200 Schermerhorn St, Brooklyn, NY 11201",
    notes: "Pedido entregado sin incidencias.",
    items: [
      { productName: "Croissant", quantity: 40 },
      { productName: "Pandebono", quantity: 20 },
    ],
  },
  {
    id: "ORD-005",
    client: "Chelsea Market Pop-up",
    date: "2026-03-20",
    amount: 190,
    status: "cancelled",
    contactChannel: "cell",
    contactValue: "+1 646 555 0199",
    address: "75 9th Ave, New York, NY 10011",
    notes: "Cliente cancelo por cambio de fecha del evento.",
    items: [{ productName: "Pandebono", quantity: 15 }],
  },
];
